---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/footandball/public_html/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp *.html $DEPLOYPATH
